package org.thelazybattley.macrotrack.ui.theme

import androidx.compose.ui.graphics.Color

data class MacroTrackColors(
    val white: Color,
    val blue: Color,
    val lightBlue: Color,
    val black: Color,
    val gray: Color,
    val green: Color,
    val orange: Color,
    val whiteSmoke: Color,
    val lightGray: Color,
    val skyBlue: Color,
    val babyBlue: Color,
    val charcoalGray: Color,
    val mediumGray: Color,
    val offWhite: Color,
    val deepBlue: Color,
    val royalBlue: Color,
    val brightBlue: Color,
    val deepBlueSplash: Color,
    val whiteSplash: Color,
    val iceBlue: Color,
    val crimsonRed: Color,
    val lightRed: Color,
    val paleBlue: Color,
    val lightGreen: Color,
    val freshGreen: Color,
    val mossGreen: Color,
    val lightAqua: Color,
    val classicGray: Color,
    val deepNavy: Color,
    val white55: Color,
    val iceMist: Color,
    val mintGreen:Color,
    val seafoamGreen:Color,
    val azureBlue:Color,
    val cream:Color,
    val coffeeBrown:Color,
    val rose:Color,
    val wineRed:Color,
    val emeraldGreen: Color,
    val cyanBlue: Color,
    val amber: Color,
)
